config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  
  #施設管理ユーザーのログイン用ルーティング
  # get 'facilities/new'
  get  '/facilities_signup',  to: 'facilities#new'
  get    '/facilities_login',   to: 'sessions#facilities_new'
  post   '/facilities_login',   to: 'sessions#facilities_create'
  delete '/facilities_logout',  to: 'sessions#facility_destroy'
  
  #一般ユーザーのログイン用ルーティング
  get 'users/new'
  get '/home', to:'static_pages#home'
  # get '/login', to:'static_pages#login'
  get '/about_hsp', to:'static_pages#about_hsp'
  get '/signup', to:'users#new'
  
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#user_destroy'
  
  #施設登録用ルーティング
  get '/add_my_facilities', to: 'my_facilities#new'
  post   '/add_my_facilities',   to: 'my_facilities#create'
  
  #static_pages用ルーティング
  get '/about_pax', to:'static_pages#about_pax'
  
  #施設検索用ルーティング
  get '/restraunt', to:'my_facilities#restraunt_index'
  get '/park', to:'my_facilities#park_index'
  get '/library', to:'my_facilities#library_index'
  get '/museum', to:'my_facilities#museum_index'
  get '/temple', to:'my_facilities#temple_index'
  get '/other', to:'my_facilities#other_index'
  
  
 
  resources :users
  resources :facilities
  resources :my_facilities, only:[:create, :destroy, :show] do
    resources :reviews, only: [:index, :create]
  end
  resources :favorites, only: [:create, :destroy]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
  
  def signup
  end

  def login
  end
  
  def about_hsp
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about_hsp.html.erb
<% provide(:title, "HSPとは？") %>
    
<div class="about_hsp">
    <div class="first_section">
        <div class="sentence">
            <h1>周りの人の気持ちばかり気になって疲れてしまう<br>
                周囲の音・音・匂いに敏感<br>
                ちょっとしたことにもびっくりしてしまう
            </h1>
            <p>
                <br>毎日がこのような経験の連続だと言う方、いませんか？<br>
                平日は通勤電車の人混みに圧倒され、会社の人間関係には人一倍気を遣い、<br>
                なんとなく人より仕事が遅くて「自分はダメだなあ」なんて悩んでしまったり。。<br>
                休日は本当はやりたい事もたくさんあるはずなのに、自分の部屋で一日体力回復。。<br><br>
    
                そんなあなたはもしかしたら「繊細さん」かもしれません。<br>
                正式には ”Highly Sensitive Person (HSP) ”と言う特性を持つ方なのですが、<br>
                最近ではよく「繊細さん」という言葉を耳にするようになりました。<br>
                「世の中の約５人に１人は繊細さんである」と言われているくらい、実は身近にいる存在です。<br><br>
    
                繊細さんたちはその言葉の通り、私たちが日頃受ける「音、光、匂い、感情、痛み・・・」<br>
                といったあらゆる刺激に敏感に反応してしまう人たちです。<br>
                だけど間違えないで欲しいのは、「繊細さんは決して病気ではない」ということ。<br>
                なので人より少しだけ繊細なあなたは、決して自分を変えようとする必要はありません。<br>
                あなたは人より繊細な性格というだけで、素晴らしい存在なのです。
            </p>
        </div>
        <img src="/assets/4019748_m.jpg" alt="talk" class="first-img">
    </div>
    <div class="second_section">
        <div class="second_sentence">
            <img src="/assets/N825_wankoperori_TP_V.jpg" alt="wanko" class="second-img">
            <p>
                <br><br><br>人より少しだけ繊細なあなたは苦手なことがたくさんあると思います。<br>
                でもあなたには他の人にはない得意な事もあるはずです。<br>
                例えば、<br><br>
                ・人の気持ちを察して共感すること<br>
                ・実直にコツコツと、ミスなく仕事をすること<br>
                ・自分なりの視点で深く考え抜くこと<br><br>
                これらは多くの繊細さんが得意としている事です。<br>
                苦手なことだけではなく、あなたが得意なことにもしっかり目を向けて、自分を褒めてあげましょう。<br><br><br>
                繊細なあなたの毎日が、Paxを通して少しでも安らげる毎日に変わりますように。
            </p>
        </div>
    </div>
</div>

app/views/static_pages/about_pax.html.erb
<% provide(:title, "Paxについて") %>
   <div class="about_hsp">
    <div class="Pax_section">
        <div class="Pax_first_sentence">
            <h1>What is Pax?</h1>
            <img src="/assets/pexels-ákos-szabó-440731.jpg" alt="glasslands" class="glasslands-img">
            <h2>Paxは繊細さんが、繊細さんの目線で<br>安らげる場所を探すためのサイトです。</h2>
            <p>
                <br>世の中は非繊細さん、つまり「鈍感さん」の方が多いため、鈍感さんを基準に形作られています。<br>
                「繊細さん目線でいろんなお店や施設を評価するサービスがあってもいいじゃないか！」<br>
                「繊細さんがもっと休日を落ち着いて安らげるような世界を作りたい！」<br>
                という思いを形にしました。<br><br>
                とはいえ、本当は開発者である私は「超」がつくほどの鈍感さんです。<br>
                かなりのマイペースで人の気持ちを察するのが苦手、細かいことは気にしない、、、<br>
                繊細さんとは真逆なのです（むしろ多少繊細になった方がいい）。<br><br>
                そんな私がなぜ繊細さんの日常のために動いているかというと、私の妻が繊細さんであることがきっかけです。<br><br>
                同じ大学の心理学部で出会った私たちは、（比較的）真面目に心理学を研究していました。<br>
                当時の私は繊細さんという概念は全く知りませんでしたし、彼女も自分が繊細さんだと知らなかったそうです。<br>
                しかしあるとき彼女は授業でHSPという概念を知り、その特徴が自分に当てはまっていることに気づきました。<br>
                そして私にもその概念を教えてくれ、「彼女がHSPだ」ということが妙に腑に落ちる感覚があったのです。<br><br>
                
                その後繊細さんについて調べれば調べるほど、繊細な彼女の心をとてもよく理解できました。<br>
                あまり自分自身には自身が持てないことが多くて、大きな音や強い光などが苦手なこと。<br>
                その反面、人の心を思いやることができて、慎重にミスなく処理することが得意だということ。<br>
                そういうことを知れば知るほど、彼女は生きにくさはあっても、素晴らしい力を持った人なんだということが分かりました。<br><br>
                しかしどれだけ理解できても、私にはどうしようもない辛さを抱えているという事実に、無力感を抱きました。<br>
                仕事終わりにどれだけの精神疲労を抱えていて、休日に外出するとすごく楽しそうにしていても家に帰るとそれが嘘のようにぐったりしている。<br>
                そんな時彼女は私にどうして欲しいのかがわからない。<br>
                お互いの気持ちがすれ違うことも多々ありました。<br><br>
                だからせめて彼女には休みの日くらいは自分のお気に入りの場所を見つけて、その場所で安らぎを感じてほしいです。<br>
                もっと言うなら「世の中全ての繊細さんに、もっと安らぎに満ちた日常を送ってほしい」とも思うようになりました。<br>
                そういう経緯で、冒頭に述べた思いをこのサイト上で形にしてみることにしました。<br><br>
                繊細な皆さんのお気に入りの場所がPaxをきっかけに見つかれば嬉しいです。<br>
                そして皆さんなりの感想を投稿してくれたら、他の繊細さんの助けになるかもしれません。<br>
                そういう素敵な循環が作れたら私は最高です！<br><br>
                素晴らしい力を持った繊細さんたちが１００％の力を発揮できるように、まずはしっかり休息を。<br>
                Paxを通してあなたの毎日が安らぎに溢れていくことを心から願っています。
            </p>
        </div>
    </div>
</div>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<div class="main-visual">
  <div class="main-visual-top-img">
  </div>
  <div class="main-visual-inner">
    <p>心落ち着ける毎日を</p>
    <p>Paxと共に</p>
  </div>
</div>

<!--サービス説明蘭-->
<div class="service-outline">
  <div class="services">
    <h1>Paxでできること</h1>
    <div class="service">
      <img src="/assets/虫眼鏡の無料アイコン10.jpeg" alt="find" class="service-img">
      <h2>見つける</h2>
      <P>ここに「見つける」の説明を入れます</P>
    </div>
    <div class="service">
      <img src="/assets/カレンダーのフリーアイコン20.jpeg" alt="reservation" class="service-img">
      <h2>予約する</h2>
      <P>ここに「予約する」の説明を入れます</P>
    </div>
    <div class="service">
      <img src="/assets/吹き出しのアイコン6.jpeg" alt="reputation" class="service-img">
      <h2>口コミをみる</h2>
      <P>ここに「口コミをみる」の説明を入れます</P>
    </div>
  </div>
</div>

<!--サービスラインナップ-->
<div class="facilities">
  <div class="facility">
    <div class="rain">
      <a class="btn btn-link" href="restraunt"><img src="/assets/4030290_m.jpeg" alt="restraunt" class="facility-img"></a><br>
      <%= link_to "飲食店", restraunt_path, id: "restraunt", class: "Editlink" %>
    </div>
    <div class="rain">
      <a class="btn btn-link" href="park"><img src="/assets/059fj21329_TP_V.jpeg" alt="park" class="facility-img"></a><br>
      <%= link_to "公園", park_path, id: "park", class: "Editlink" %>
    </div>
    <div class="rain">
      <a class="btn btn-link" href="library"><img src="/assets/elly20160628465420_TP_V.jpeg" alt="library" class="facility-img"></a><br>
      <%= link_to "図書館", library_path, id: "library", class: "Editlink" %>
    </div>
    <div class="rain">
      <a class="btn btn-link" href="temple"><img src="/assets/kyotoDSC_64430190_TP_V.jpg" alt="shrine/temple" class="facility-img"></a><br>
      <%= link_to "神社・お寺", temple_path, id: "temple", class: "Editlink" %>
    </div>
    <div class="rain">
      <a class="btn btn-link" href="museum"><img src="/assets/susipakuAB861PAKU8711_TP_V.jpeg" alt="museum" class="facility-img"></a><br>
      <%= link_to "美術館・博物館", museum_path, id: "museum", class: "Editlink" %>
    </div>
    <div class="rain">
      <a class="btn btn-link" href="other"><img src="/assets/RED19923036_TP_V.jpeg" alt="others" class="facility-img"></a><br>
      <%= link_to "その他", other_path, id: "other", class: "Editlink" %>
    </div>
  </div>
</div>

app/views/static_pages/signup.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Sign up | Pax</title>
  </head>
  <body>
    
  </body>
</html>