config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  
  #施設管理ユーザーのログイン用ルーティング
  # get 'facilities/new'
  get  '/facilities_signup',  to: 'facilities#new'
  get    '/facilities_login',   to: 'sessions#facilities_new'
  post   '/facilities_login',   to: 'sessions#facilities_create'
  delete '/facilities_logout',  to: 'sessions#facility_destroy'
  
  #一般ユーザーのログイン用ルーティング
  get 'users/new'
  get '/home', to:'static_pages#home'
  # get '/login', to:'static_pages#login'
  get '/about_hsp', to:'static_pages#about_hsp'
  get '/signup', to:'users#new'
  
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#user_destroy'
  
  #施設登録用ルーティング
  get '/add_my_facilities', to: 'my_facilities#new'
  post   '/add_my_facilities',   to: 'my_facilities#create'
  
  #static_pages用ルーティング
  get '/about_pax', to:'static_pages#about_pax'
  
  #施設検索用ルーティング
  get '/restraunt', to:'my_facilities#restraunt_index'
  get '/park', to:'my_facilities#park_index'
  get '/library', to:'my_facilities#library_index'
  get '/museum', to:'my_facilities#museum_index'
  get '/temple', to:'my_facilities#temple_index'
  get '/other', to:'my_facilities#other_index'
  
  
 
  resources :users
  resources :facilities
  resources :my_facilities, only:[:create, :destroy, :show] do
    resources :reviews, only: [:index, :create]
  end
  resources :favorites, only: [:create, :destroy]
end

app/models/my_facility.rb
class MyFacility < ApplicationRecord
  mount_uploader :top_image, TopImageUploader
  has_many :reviews, dependent: :destroy
  belongs_to :facility
  has_many :favorites, foreign_key: 'my_facility_id', dependent: :destroy     # 記事/お気に入り → 1:多
  belongs_to :user, optional: true
  has_many :users, through: :favorites
  default_scope -> { order(created_at: :desc) }
  with_options presence: true do
  validates :facility_name
  validates :kana
  validates :category
  validates :address
  validates :top_image
   with_options uniqueness: true do
     validates :phone_number
     validates :email
   end
  end
  
  def avg_score
    unless self.reviews.empty?
      reviews.average(:score).round(1).to_f
    else
      0.0
    end
  end

  def review_score_percentage
    unless self.reviews.empty?
      reviews.average(:score).round(1).to_f*100/5
    else
      0.0
    end
  end
end

app/controllers/my_facilities_controller.rb
class MyFacilitiesController < ApplicationController
  before_action :logged_in_facility, only: [:create, :destroy]
  
  def show
    @my_facility = MyFacility.find(params[:id])
    @review = Review.new
  end
  
  def new
    @my_facility = MyFacility.new
  end
    
  def create
    @my_facility = current_facility.my_facilities.build(my_facility_params)
    if @my_facility.save
      flash[:success] = "施設を登録しました"
      redirect_to current_facility
    else
      render 'new'
    end
  end
  
  def restraunt_index
    @my_facilities = MyFacility.where(category: "飲食店")
  end
  
  def park_index
    @my_facilities = MyFacility.where(category: "公園")
  end
  
  def library_index
    @my_facilities = MyFacility.where(category: "図書館")
  end
  
  def temple_index
    @my_facilities = MyFacility.where(category: "神社・お寺")
  end
  
  def museum_index
    @my_facilities = MyFacility.where(category: "美術館・博物館")
  end
  
  def other_index
    @my_facilities = MyFacility.where(category: "その他")
  end

  
  private

    def my_facility_params
      params.require(:my_facility).permit(:facility_name, :branch_name, :kana, :category,
                                          :address, :phone_number, :email, :services, :top_image, 
                                          :other_image, :opening_days, :opening_hours, :access, 
                                          :parking_lot, :seats, :details)
    end
end

app/helpers/my_facilities_helper.rb
module MyFacilitiesHelper
end

app/views/my_facilities/_my_facilities.html.erb
<li id="my_facilities-<%= my_facility.id %>">
  <span class="facility"><%= link_to my_facility.facility.name, my_facility.facility %></span>
  <span class="facility_name"><%= my_facility.facility_name %></span>
  <span class="branch_name"><%= my_facility.branch_name %></span>
</li>

app/views/my_facilities/_my_facility.html.erb
<li id="my_facilities-<%= my_facility.id %>">
  <span class="facility_name"><%= my_facility.facility_name %></span>
  <span class="branch_name"><%= my_facility.branch_name %></span>
</li>
<p>このファイルだよーん</p>

app/views/my_facilities/add_my_facilities.html.erb
<% provide(:title, "施設登録") %>
<div class="main">
  <h1>新規施設登録</h1>
  
  <div class="form">
    <%= form_with(model: @my_facility, local: true) do |f| %>
      
      <%= f.label :facility_name, "施設名" %>
      <%= f.text_field :facility_name, class: 'form-control' %>
    
      <%= f.label :branch_name, "支店名" %>
      <%= f.text_field :branch_name, class: 'form-control' %>

      <%= f.label :kana, "ヨミガナ" %>
      <%= f.text_field :kana, class: 'form-control' %>
      
      <%= f.label :category, "施設カテゴリー" %>
      <%= f.select :category,
        [["飲食店", "飲食店"], ["公園", "公園"], ["図書館", "図書館"], ["神社・お寺", "神社・お寺"],
        ["美術館・博物館", "美術館・博物館"], ["その他", "その他"]], include_blank: "選択して下さい"%>
    
      <%= f.label :address, "住所" %>
      <%= f.text_field :address, class: 'form-control' %>
    
      <%= f.label :access, "アクセス" %>
      <%= f.text_field :access, class: 'form-control' %>
    
      <%= f.label :phone_number, "電話番号" %>
      <%= f.text_field :phone_number, class: 'form-control' %>
    
      <%= f.label :email, "メールアドレス" %>
      <%= f.email_field :email, class: 'form-control' %>
    
      <%= f.label :services, "サービス概要" %>
      <%= f.text_field :services, class: 'form-control' %>
    
      <%= f.label :top_image, "トップ画像" %>
      <%= f.file_field :top_image, id: :top_image %>
    
      <%= f.label :other_image, "その他イメージ画像を登録してもらおうと思ったけど、この時点では必要ないかもしれないので保留" %>
      <%= f.text_field :other_image, class: 'form-control' %>
    
      <%= f.label :opening_days, "営業日" %>
      <%= f.text_field :opening_days, class: 'form-control' %>
    
      <%= f.label :opening_hours, "営業時間" %>
      <%= f.text_field :opening_hours, class: 'form-control' %>
    
      <%= f.label :parking_lot, "駐車場の数（半角数字）" %>
      <%= f.text_field :parking_lot, class: 'form-control' %>
    
      <%= f.label :seats, "座席数（半角数字）" %>
      <%= f.text_field :seats, class: 'form-control' %>
    
      <%= f.label :details, "施設詳細" %>
      <%= f.text_field :details, class: 'form-control' %>

      <%= f.submit "登録", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/my_facilities/facility_my_page.html.erb
<% provide(:title, "マイページ") %>

<div class="top-wrapper">
  <img src-"#" class="facility_image" alt="施設管理ユーザーのトップ画像">
  <h1>
    <!--<%= @facility.name %>-->
  </h1>
</div>
<h1>施設管理ユーザーのマイページ</h1>

app/views/my_facilities/library_index.html.erb
<ul class="main_contents">
  <% @my_facilities.each do |park| %>
    <li class="details">
　          <%= image_tag park.top_image.url, alt: "top_image", class:"top_image information" %>
　          <div>
          <%= link_to park.facility_name, park, class:"facility_name" %><br>
          <%= park.address %><br>
          <%= park.opening_days %><br>
          <%= park.opening_hours %><br>
　          </div>
    </li>
  <% end %>
  <div class="clear" ></div>
</ul>

app/views/my_facilities/museum_index.html.erb
<ul class="main_contents">
  <% @my_facilities.each do |park| %>
    <li class="details">
　          <%= image_tag park.top_image.url, alt: "top_image", class:"top_image information" %>
　          <div>
          <%= link_to park.facility_name, park, class:"facility_name" %><br>
          <%= park.address %><br>
          <%= park.opening_days %><br>
          <%= park.opening_hours %><br>
　          </div>
    </li>
  <% end %>
  <div class="clear" ></div>
</ul>

app/views/my_facilities/new.html.erb
<% provide(:title, "施設登録") %>
<div class="main">
  <h1>新規施設登録</h1>
  
  <div class="form">
    <%= form_with(model: @my_facility, local: true) do |f| %>
    <%= render 'shared/my_facility_error_messages' %>
      
      <%= f.label :facility_name, "施設名" %>
      <%= f.text_field :facility_name, class: 'form-control' %>
    
      <%= f.label :branch_name, "支店名" %>
      <%= f.text_field :branch_name, class: 'form-control' %>

      <%= f.label :kana, "ヨミガナ" %>
      <%= f.text_field :kana, class: 'form-control' %>
      
      <%= f.label :category, "施設カテゴリー" %>
      <%= f.select :category,
        [["飲食店", "飲食店"], ["公園", "公園"], ["図書館", "図書館"], ["神社・お寺", "神社・お寺"],
        ["美術館・博物館", "美術館・博物館"], ["その他", "その他"]], include_blank: "選択して下さい"%>
    
      <%= f.label :address, "住所" %>
      <%= f.text_field :address, class: 'form-control' %>
    
      <%= f.label :access, "アクセス" %>
      <%= f.text_field :access, class: 'form-control' %>
    
      <%= f.label :phone_number, "電話番号" %>
      <%= f.text_field :phone_number, class: 'form-control' %>
    
      <%= f.label :email, "メールアドレス" %>
      <%= f.email_field :email, class: 'form-control' %>
    
      <%= f.label :services, "サービス概要" %>
      <%= f.text_field :services, class: 'form-control' %>
    
      <%= f.label :top_image, "トップ画像" %>
      <%= f.file_field :top_image, id: :top_image %>
    
      <%= f.label :other_image, "その他イメージ画像を登録してもらおうと思ったけど、この時点では必要ないかもしれないので保留" %>
      <%= f.text_field :other_image, class: 'form-control' %>
    
      <%= f.label :opening_days, "営業日" %>
      <%= f.text_field :opening_days, class: 'form-control' %>
    
      <%= f.label :opening_hours, "営業時間" %>
      <%= f.text_field :opening_hours, class: 'form-control' %>
    
      <%= f.label :parking_lot, "駐車場の数（半角数字）" %>
      <%= f.text_field :parking_lot, class: 'form-control' %>
    
      <%= f.label :seats, "座席数（半角数字）" %>
      <%= f.text_field :seats, class: 'form-control' %>
    
      <%= f.label :details, "施設詳細" %>
      <%= f.text_field :details, class: 'form-control' %>

      <%= f.submit "登録", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/my_facilities/other_index.html.erb
<ul class="main_contents">
  <% @my_facilities.each do |restraunt| %>
    <li class="details">
　          <%= image_tag restraunt.top_image.url, alt: "top_image", class:"top_image information" %>
　          <div>
          <%= link_to restraunt.facility_name, restraunt, class:"facility_name" %><br>
          <%= restraunt.address %><br>
          <%= restraunt.opening_days %><br>
          <%= restraunt.opening_hours %><br>
　          </div>
    </li>
  <% end %>
  <div class="clear" ></div>
</ul>

app/views/my_facilities/park_index.html.erb
<ul class="main_contents">
  <% @my_facilities.each do |park| %>
    <li class="details">
      <%= image_tag park.top_image.url, alt: "top_image", class:"top_image information" %>
      <div>
        <%= link_to park.facility_name, park, class:"facility_name" %><br>
        <%= park.address %><br>
        <%= park.opening_days %><br>
        <%= park.opening_hours %><br>
      </div>
    </li>
  <% end %>
  <div class="clear" ></div>
</ul>

app/views/my_facilities/restraunt_index.html.erb
<ul class="main_contents">
  <% @my_facilities.each do |restraunt| %>
    <li class="details">
        <%= image_tag restraunt.top_image.url, alt: "top_image", class:"top_image information" %>
        <div>
            <%= link_to restraunt.facility_name, restraunt, class:"facility_name" %><br>
            <%= restraunt.address %><br>
            <%= restraunt.opening_days %><br>
            <%= restraunt.opening_hours %><br>
        </div>
    </li>
  <% end %>
  <div class="clear" ></div>
</ul>

app/views/my_facilities/show.html.erb
<div class="my_facility_pages">
  <div class="sidebar">
    <h1>
      広告枠
    </h1>
  </div>
  <div class="my_facility_about">
    <%= image_tag @my_facility.top_image.url, alt: "top_image", class:"my_facility_pages_top_image" %>
    <div class="rating">
      <h1>
        <%= @my_facility.facility_name %> <%= @my_facility.branch_name %>
      </h1>
      <div>
        <div class="content average-score">
          <div class="star-rating mb-2">
            <div class="star-rating-back">★★★★★</div>
            <div class="star-rating-front" style="width: <%= @my_facility.review_score_percentage %>%">★★★★★</div>
          </div>
          <div class="average-score-display ml-3 pt-2">
            <%= @my_facility.avg_score %>点（<%= @my_facility.reviews.count %>件のレビュー）
          </div>
   
        </div>
        <p>落ち着いた雰囲気（ここにタグを配置）</p>
      </div>
    </div>
    <div class="clear"></div>
  </div>
  <div class="my_facility_about">
    <h1>
      ここに各施設のイメージ画像を貼る
    </h1>
  </div>
  <div class="my_facility_about">
  　<%= render 'reviews/form', review: @review, my_facility: @my_facility %>
  　<p>ここにクチコミの一部を掲載</p>
  　<%= link_to "他のレビューを見る", my_facility_reviews_path(@my_facility), class: "button light ml-3 mt-3" %>
  　<% if current_user.check_favorite?(@my_facility) %>
      <%= form_with(model: current_user.favorites.find_by(my_facility_id: @my_facility.id), local: true, method: :delete) do |f| %>
        <%= hidden_field_tag :my_facility_id, @my_facility.id %>
        <%= f.submit '登録解除', class: 'btn btn-danger' %>
      <% end %>
    <% else %>
      <%= form_with(model: current_user.favorites.build, local: true) do |f| %>
        <%= hidden_field_tag :my_facility_id, @my_facility.id %>
        <%= f.submit 'お気に入り登録', class: 'btn btn-primary' %>
      <% end %>
    <% end %>
  </div>
  <div class="my_facility_about">
    <table>
    	<tr>
    		<th>施設名</th>
    		<td><%= @my_facility.facility_name %></td>
    	</tr>
    	<tr>
    		<th>ジャンル</th>
    		<td><%= @my_facility.category %></td>
    	</tr>
    	<tr>
    		<th>住所</th>
    		<td><%= @my_facility.address %></td>
    	</tr>
    	<tr>
    		<th>アクセス</th>
    		<td><%= @my_facility.access %></td>
    	</tr>
    	<tr>
    		<th>問い合わせ</th>
    		<td><%= @my_facility.phone_number %></td>
    	</tr>
    	<tr>
    		<th>営業日</th>
    		<td><%= @my_facility.opening_days %></td>
    	</tr>
    	<tr>
    		<th>営業時間</th>
    		<td><%= @my_facility.opening_hours %></td>
    	</tr>
    	<tr>
    		<th>駐車場</th>
    		<td><%= @my_facility.parking_lot %></td>
    	</tr>
    	<tr>
    		<th>座席数</th>
    		<td><%= @my_facility.seats %></td>
    	</tr>
    	<tr>
    		<th>その他詳細</th>
    		<td><%= @my_facility.details %></td>
    	</tr>
    </table>
  </div>
</div>  

app/views/my_facilities/temple_index.html.erb
<ul class="main_contents">
  <% @my_facilities.each do |park| %>
    <li class="details">
　          <%= image_tag park.top_image.url, alt: "top_image", class:"top_image information" %>
　          <div>
          <%= link_to park.facility_name, park, class:"facility_name" %><br>
          <%= park.address %><br>
          <%= park.opening_days %><br>
          <%= park.opening_hours %><br>
　          </div>
    </li>
  <% end %>
  <div class="clear" ></div>
</ul>