config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  
  #施設管理ユーザーのログイン用ルーティング
  # get 'facilities/new'
  get  '/facilities_signup',  to: 'facilities#new'
  get    '/facilities_login',   to: 'sessions#facilities_new'
  post   '/facilities_login',   to: 'sessions#facilities_create'
  delete '/facilities_logout',  to: 'sessions#facility_destroy'
  
  #一般ユーザーのログイン用ルーティング
  get 'users/new'
  get '/home', to:'static_pages#home'
  # get '/login', to:'static_pages#login'
  get '/about_hsp', to:'static_pages#about_hsp'
  get '/signup', to:'users#new'
  
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#user_destroy'
  
  #施設登録用ルーティング
  get '/add_my_facilities', to: 'my_facilities#new'
  post   '/add_my_facilities',   to: 'my_facilities#create'
  
  #static_pages用ルーティング
  get '/about_pax', to:'static_pages#about_pax'
  
  #施設検索用ルーティング
  get '/restraunt', to:'my_facilities#restraunt_index'
  get '/park', to:'my_facilities#park_index'
  get '/library', to:'my_facilities#library_index'
  get '/museum', to:'my_facilities#museum_index'
  get '/temple', to:'my_facilities#temple_index'
  get '/other', to:'my_facilities#other_index'
  
  
 
  resources :users
  resources :facilities
  resources :my_facilities, only:[:create, :destroy, :show] do
    resources :reviews, only: [:index, :create]
  end
  resources :favorites, only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
<footer>
    <!--<div class="footer-logo">-->
    <!--  <%= link_to "Pax", root_path %>-->
    <!--</div>-->
    <div class="footer-left footer-contents">
      <h3>Paxとは</h3>
        <ul>
          <li><%= link_to "Paxについて", about_pax_path, class: "Editlink" %></li>
          <li><%= link_to "チームメンバー", "#", class: "Editlink" %></li>
          <li><%= link_to "サイトマップ", "#", class: "Editlink" %></li>
        </ul>
    </div>
    <div class="footer-rights footer-contents">
      <h3>法人の方はこちら</h3>
        <ul>
          <li><%= link_to "無料会員登録", facilities_signup_path, class: "Editlink" %></li>
          <li><%= link_to "ログイン", facilities_login_path, class: "Editlink" %></li>
          <li><%= link_to "Paxを使ってお店をPRしましょう！", "#", class: "Editlink" %></li>
        </ul>
    </div>
    <div class="footer-center footer-contents">
      <h3>ヘルプ・サポート</h3>
        <ul>
          <li><%= link_to "FAQ", "#", class: "Editlink" %></li>
          <li><%= link_to "お問い合わせ", "#", class: "Editlink" %></li>
          <li><%= link_to "利用規約", "#", class: "Editlink" %></li>
          <li><%= link_to "プライバシーポリシー", "#", class: "Editlink" %></li>
        </ul>
    </div>
    <div class="clear"></div>
  </footer>

app/views/layouts/_header.html.erb
    <header>
      <div class="header-logo">
        <%= link_to "Pax", root_path, class: "Editlink" %>
      </div>
      <div class="header-list">
        <ul>
          <li><%= link_to "繊細さんって？", about_hsp_path, class: "Editlink" %></li>
          <% if user_logged_in? %>
          <li><%= link_to "お気に入りを探す", href="/#restraunt", class: "Editlink" %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "マイページ更新", current_user, class: "Editlink" %></li>
              <li><%= link_to "お気に入り", '#', class: "Editlink" %></li>
              <li><%= link_to "口コミ", '#', class: "Editlink" %></li>
              <li>
                <%= link_to "ログアウト", logout_path, class: "Editlink", method: :delete %>
              </li>
            </ul>
          </li>
          <% elsif facility_logged_in? %>
            <li><%= link_to "施設登録", add_my_facilities_path, class: "Editlink" %></li>
            <li><%= link_to "マイページ", facility_path(id: current_facility.id), class: "Editlink" %></li>
            <li><%= link_to "ログアウト", facilities_logout_path, method: :delete, class: "Editlink" %></li>
          <% else %>
            <li><%= link_to "新規登録", signup_path, class: "Editlink" %></li>
            <li><%= link_to "ログイン", login_path, class: "Editlink" %></li>
          <% end %>
        </ul>
      </div>
      <div class="clear"></div>
    </header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>s

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Pax</title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
    <script src="https://kit.fontawesome.com/484e6509e8.js" crossorigin="anonymous"></script>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  

  <body>
    <%= render 'layouts/header' %>
    
    <div class="containers">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>